// This file has been generated by Specta. DO NOT EDIT.

export type TestType = { awa: string; wawa: number };

/**
 * ```md
 * |                                            worker
 * |                                            │     process
 * | timestamp                                  │     │     increment
 * | │                                          │     │     │
 * | 111111111111111111111111111111111111111111 11111 11111 111111111111
 * | 63                                        22    17    12          0
 *
 * Max values:
 * worker: 31
 * process: 31
 * increment: 4095
 * ```
 */
export type Snowflake = string;

export const Routes = {};

Object.freeze(Routes);
