// This file has been generated by Specta. DO NOT EDIT.

export type CreateMessageRequest = {
  messageParts: MessagePart[];
  threadId: string;
  responseMessageId: string;
  model: string;
  modelParams: ModelParamsRequest | null;
};

export type MessagePart = { type: 'text'; text: string };

export type ModelParamsRequest = { reasoningEffort: string; includeSearch: boolean };

export type TestType = { awa: string; wawa: number };

/**
 * ```md
 * |                                            worker
 * |                                            │     process
 * | timestamp                                  │     │     increment
 * | │                                          │     │     │
 * | 111111111111111111111111111111111111111111 11111 11111 111111111111
 * | 63                                        22    17    12          0
 *
 * Max values:
 * worker: 31
 * process: 31
 * increment: 4095
 * ```
 */
export type Snowflake = string;

export const Routes = {
  /**
   * Route for:
   * - POST `message`
   */
  message: () => 'message' as const,
};

Object.freeze(Routes);
